config/routes.rb
Store::Application.routes.draw do
  #sites controller
  root 'sites#index'

  #products controller
    get '/products', to: 'products#index', as: 'products'
    
    get '/products/new', to: 'products#new', as: :new_product

    get '/products/:id', to: 'products#show', as: :product

    get '/products/:id/edit', to: 'products#edit', as: :edit_product

    post '/products', to: 'products#create'

    patch '/products/:id', to: 'products#update'


  #categories controller
    get '/categories', to: 'categories#index', as: 'categories'
    
    get '/categories/new', to: 'categories#new', as: :new_category

    get '/categories/:id', to: 'categories#show', as: :category

    get '/categories/:id/edit', to: 'categories#edit', as: :edit_category

    post '/categories', to: 'categories#create'

    patch '/categories/:id', to: 'categories#update'
end
#  Prefix Verb   URI Pattern               Controller#Action
#     sites GET    /sites(.:format)          sites#index
#           POST   /sites(.:format)          sites#create
#  new_site GET    /sites/new(.:format)      sites#new
# edit_site GET    /sites/:id/edit(.:format) sites#edit
#      site GET    /sites/:id(.:format)      sites#show
#           PATCH  /sites/:id(.:format)      sites#update
#           PUT    /sites/:id(.:format)      sites#update
#           DELETE /sites/:id(.:format)      sites#destroy

#    Prefix Verb   URI Pattern                    Controller#Action
#      products GET    /products(.:format)            products#index
#               POST   /products(.:format)            products#create
#   new_product GET    /products/new(.:format)        products#new
#  edit_product GET    /products/:id/edit(.:format)   products#edit
#       product GET    /products/:id(.:format)        products#show
#               PATCH  /products/:id(.:format)        products#update
#               PUT    /products/:id(.:format)        products#update
#               DELETE /products/:id(.:format)        products#destroy
#    categories GET    /categories(.:format)          categories#index
#               POST   /categories(.:format)          categories#create
#  new_category GET    /categories/new(.:format)      categories#new
# edit_category GET    /categories/:id/edit(.:format) categories#edit
#      category GET    /categories/:id(.:format)      categories#show
#               PATCH  /categories/:id(.:format)      categories#update
#               PUT    /categories/:id(.:format)      categories#update
#               DELETE /categories/:id(.:format)      categories#destroy

app/models/association.rb
class Association < ActiveRecord::Base
	belongs_to :product
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :associations
	has_many :products, through: :associations

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :associations
	has_many :categories, through: :associations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		category = Category.create(name: params["category"]["name"])
		params["category"]["product_ids"].each { 
			|x| Association.create(product_id: x, category_id: category_id) if x != "" }
		#goes into the params hash into the product_ids hash 
		#related by "Association"

		redirect_to category
	end

	def show
		@category = Category.find(params[:id])
		@products = @category.products
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		category = Category.find(params[:id])
		updated_info = params.require(:category).permit(:name)
		category.update_attributes(updated_info)
		category.product_ids = params["category"]["product_ids"]
		redirect_to category
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		product = Product.create(name: params["product"]["name"], price: params["product"]["price"], description: params["product"]["description"])
		params["product"]["category_ids"].each { |x| Association.create(product_id: product.id, category_id: x) if x != "" }
		#goes into the params hash into the category_ids hash related by "Association"
		redirect_to product
	end

	def show
		@product = Product.find(params[:id])
		@categories = @product.categories
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		product = Product.find(params[:id])
		updated_info = params.require(:product).permit(:name, :price, :description)
		product.update_attributes(updated_info)
		product.category_ids = params["product"]["category_ids"]
		redirect_to product
	end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/categories/_category_form.html.erb
<!-- PARTIAL CATEGORY CREATE FORM -->

<%= form_for(@category) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br>
	<%= f.label "Choose products:" %> <br>
	<%= collection_check_boxes :category, :product_ids, Product.all, :id, :name %>
	<br>
	<%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<!-- EDIT CATEGORY PAGE
displays: edit category form -->

<h1>EDIT CATEGORY</h1>

<%= render "category_form" %>

app/views/categories/index.html.erb
<!-- CATEGORIES HOME PAGE
display: categories -->

<h1>Categories List</h1>
<ul>
<% @categories.each do |category| %>
	<li><%= link_to category.name, category_path(category.id) %> </li> <br>
<% end %>
</ul>

app/views/categories/new.html.erb
<!-- CREATE NEW CATEGORY
displays: new category form -->

<h1>SUBMIT NEW CATEGORY</h1>

<%= render "category_form" %>

app/views/categories/show.html.erb
<!-- SHOW CATEGORY PAGE
displays: one category with it's products -->

<h1><%= @category.name %></h1>
<h4>Products in this category:</h4>
<ul>
<% @products.each do |product| %>
	<li> <%= link_to product.name, product_path(product.id) %> </li>
<% end %>
</ul>

<h4>Edit: <%= link_to @category.name, edit_category_path %></h4>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to "Products", products_path, class: "navbar-brand" %>
<%= link_to "Categories", categories_path, class: "navbar-brand" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Store" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Store" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/products/_product_form.html.erb
<!-- PARTIAL PRODUCT CREATE FORM -->

<%= form_for(@product) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br>
	<%= f.label :price %>
	<%= f.text_field :price %><br>
	<%= f.label :description %>
	<%= f.text_field :description %><br>
	<%= f.label "Choose categories:" %> <br>
	<%= collection_check_boxes :product, :category_ids, Category.all, :id, :name %>
	<br>
	<%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<!-- EDIT PRODUCT PAGE
displays: edit product form -->

<h1>EDIT PRODUCT</h1>

<%= render "product_form" %>

app/views/products/index.html.erb
<!-- PRODUCTS PAGE
display: products -->

<h1>Products List</h1>
<ul>
<% @products.each do |product| %>
	<li><%=link_to product.name, product_path(product.id) %> -- <%= product.description %> </li> <br>
<% end %>
</ul>

app/views/products/new.html.erb
<!-- CREATE NEW PRODUCT
displays: new product form -->

<h1>SUBMIT NEW PRODUCT</h1>

<%= render "product_form" %>



	 

app/views/products/show.html.erb
<!-- SHOW PRODUCT PAGE
displays: one product with it's categories -->

<h1><%= @product.name %></h1>

<h4>Description: </h4>
<p><%= @product.description %></p>

<h4>Price: </h4>
<p><%= @product.price %></p>

<h4>Categories:</h4>
<ul>
<% @categories.each do |category| %>
	<li><%= link_to category.name, category_path(category.id) %> </li>
<% end %>
</ul>

<h4>Edit: <%= link_to @product.name, edit_product_path %></h4>

app/views/sites/index.html.erb
<!-- HOMEPAGE
displays
     links to product views
     links to category views -->

<h1>Welcome to the store administrative interface!</h1>
<h4>Please make a selection:</h4>
<h5> 1) <%= link_to "View Products", products_path %></h5>
<h5> 2) <%= link_to "View Categories", categories_path %></h5>
<h5> 3) <%= link_to "Add New Product", new_product_path %></h5>
<h5> 4) <%= link_to "Add New Category", new_category_path %></h5>